### ISSUE TITLE
Context getting too long

### ISSUE THREAD

**Issue by jqknono** [takumisoft68/vscode-markdown-toc-num#7]
Context getting too long, can you please remove it, or make it configurable?

![GvxEJLyjk7](https://user-images.githubusercontent.com/12892734/236655763-bad61dc8-5e84-439a-afe9-5b17a36e8b8e.png)

**Comment by takumisoft68** [comment]
@jqknono 
Do you mean those menu strings are too long?

**Comment by takumisoft68** [comment]
Is your request remove "markdown-toc-num: " from menu string, right?

**Comment by jqknono** [comment]
@takumisoft68 
Yes, there are too many menu items, I've to scroll in the menu sometimes.
Anyway, thanks for make the great extension, it's the best I've used.
