### ISSUE TITLE
見出しに記号が含まれる場合について

### ISSUE THREAD

**Issue by tigrebiz** [takumisoft68/vscode-markdown-toc-num#8]
見出しに「、」や「.」や「:」などの記号が含まれている場合、生成した目次に適切にリンクが貼られませんが、これは仕方がないでしょうか？

**Comment by takumisoft68** [comment]
@tigrebiz 
再現手順、所望の出力、実際の出力　を提示して現象と要望を明確にしてください。

**Comment by tigrebiz** [comment]
## 再現手順

1. 見出しを生成する

以下見出し例
```
## 見出し1

## 見出し2（記号あり）

### 見出し3

### 見出し4「記号あり」

## 見出し5

## 見出し6：記号あり

### 見出し7

### 見出し8、記号あり

```

2. プラグインを使い、右クリックからInsert/UpdateTOCで目次を生成（現状の出力）

```生成された目次
- [見出し1](#見出し1)
- [見出し2（記号あり）](#見出し2記号あり)
  - [見出し3](#見出し3)
  - [見出し4「記号あり」](#見出し4記号あり)
- [見出し5](#見出し5)
- [見出し6：記号あり](#見出し6記号あり)
  - [見出し7](#見出し7)
  - [見出し8、記号あり](#見出し8記号あり)
```

3. 作成した記事をweb上にアップロードし、その記事内の生成された目次をクリックする

すると、見出し1,3,5,7は適切にリンクが貼られているため、クリックで適切な見出しへジャンプする。
見出しの2,4,6,8はおそらく、見出しの記号が削除された状態の目次リンクが生成されているため、適切な見出しへのジャンプが行われない。


## 所望の出力

```生成されてほしい目次
- [見出し1](#見出し1)
- [見出し2（記号あり）](#見出し2（記号あり）)
  - [見出し3](#見出し3)
  - [見出し4「記号あり」](#見出し4「記号あり」)
- [見出し5](#見出し5)
- [見出し6：記号あり](#見出し6：記号あり)
  - [見出し7](#見出し7)
  - [見出し8、記号あり](#見出し8、記号あり)
```

上記のように、見出しに記号が含まれている場合であっても、適切に記号込みのリンクが生成されてほしい。
それにより記号が含まれる目次をクリックしたときにも、該当の見出し箇所へ適切にジャンプしてほしい。


以上ですが、伝わりますでしょうか？
よろしくお願いいたします。

**Comment by tigrebiz** [comment]
@takumisoft68 
下記、よろしくお願いします。

## 再現手順

1. 見出しを生成する

以下見出し例
```
## 見出し1

## 見出し2（記号あり）

### 見出し3

### 見出し4「記号あり」

## 見出し5

## 見出し6：記号あり

### 見出し7

### 見出し8、記号あり

```

2. プラグインを使い、右クリックからInsert/UpdateTOCで目次を生成（現状の出力）

```生成された目次
- [見出し1](#見出し1)
- [見出し2（記号あり）](#見出し2記号あり)
  - [見出し3](#見出し3)
  - [見出し4「記号あり」](#見出し4記号あり)
- [見出し5](#見出し5)
- [見出し6：記号あり](#見出し6記号あり)
  - [見出し7](#見出し7)
  - [見出し8、記号あり](#見出し8記号あり)
```

3. 作成した記事をweb上にアップロードし、その記事内の生成された目次をクリックする

すると、見出し1,3,5,7は適切にリンクが貼られているため、クリックで適切な見出しへジャンプする。
見出しの2,4,6,8はおそらく、見出しの記号が削除された状態の目次リンクが生成されているため、適切な見出しへのジャンプが行われない。


## 所望の出力

```生成されてほしい目次
- [見出し1](#見出し1)
- [見出し2（記号あり）](#見出し2（記号あり）)
  - [見出し3](#見出し3)
  - [見出し4「記号あり」](#見出し4「記号あり」)
- [見出し5](#見出し5)
- [見出し6：記号あり](#見出し6：記号あり)
  - [見出し7](#見出し7)
  - [見出し8、記号あり](#見出し8、記号あり)
```

上記のように、見出しに記号が含まれている場合であっても、適切に記号込みのリンクが生成されてほしい。
それにより記号が含まれる目次をクリックしたときにも、該当の見出し箇所へ適切にジャンプしてほしい。


以上ですが、伝わりますでしょうか？
よろしくお願いいたします。

**Comment by takumisoft68** [comment]
vscode アンカーモードにおいて、「」はアンカーが正しく動作していないようですが、：、はアンカーが正しく設定されていました。
「」のみ修正します

**Comment by tigrebiz** [comment]
@takumisoft68 
ご対応ありがとうございます。
「」に関しては正しくリンクが生成されるようになりました。その他（）、：などは私の環境ではうまく生成されませんでした、、。
Windows11でVSCode1.83を利用しています。拡張機能などはすべて無効にして試しました。

下記のような状態です。
```
## 見出し1
## 見出し2（記号あり）
### 見出し3
### 見出し4「記号あり」
## 見出し5
## 見出し6：記号あり
### 見出し7
### 見出し8、記号あり

<!-- TOC tocDepth:2..3 chapterDepth:2..6 -->
- [この記事の目的](#この記事の目的)
- [目次](#目次)
- [見出し1](#見出し1)
- [見出し2（記号あり）](#見出し2記号あり)
  - [見出し3](#見出し3)
  - [見出し4「記号あり」](#見出し4「記号あり」)
- [見出し5](#見出し5)
- [見出し6：記号あり](#見出し6記号あり)
  - [見出し7](#見出し7)
  - [見出し8、記号あり](#見出し8記号あり)
  <!-- /TOC -->
```
